presence/urls.py
from django.conf import settings
from django.conf.urls.defaults import patterns, include, url
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.generic.simple import direct_to_template


admin.autodiscover()


urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', 'apps.views.dashboard', name='dashboard'),
    url(r'^login/$', 'django.contrib.auth.views.login',
        {'template_name': 'login.html'}, name='login'),
    url(r'^logout/$', 'people.views.logout', name='logout'),
    url(r'^workflow/', include('workflow.urls')),
    url(r'^activation/', include('activation.urls')),
    url(r'^shout/', include('shout.urls')),
    url(r'^people/', include('people.urls')),
    url(r'^vote/', include('vote.urls')),
    url(r'^event/', include('event.urls')),
    url(r'^planning/', include('planning.urls')),
    url(r'^activity-ajax/$', 'apps.views.activity_ajax', name='activity-ajax'),
)

urlpatterns += patterns("",
    (r'^robots\.txt$', direct_to_template,
         {'template': 'robots.txt', 'mimetype': 'text/plain'}),
    (r'^humans\.txt$', direct_to_template,
         {'template': 'humans.txt', 'mimetype': 'text/plain'}),
    (r'^hacker\.txt$', direct_to_template,
         {'template': 'hacker.txt', 'mimetype': 'text/plain'}),
    (r'^license\.txt$', direct_to_template,
         {'template': 'license.txt', 'mimetype': 'text/plain'}),
    (r'^python\.txt$', direct_to_template,
         {'template': 'python.txt', 'mimetype': 'text/plain'}),
    )


if settings.LOCAL_DEVELOPMENT:
    urlpatterns += staticfiles_urlpatterns()

if settings.LOCAL_DEVELOPMENT:
    urlpatterns += patterns("django.views",
        url(r"%s(?P<path>.*)$" % settings.MEDIA_URL[1:], "static.serve", {
            "document_root": settings.MEDIA_ROOT,
        })
    )

presence/apps/activity/models.py
import base64
try:
    import cPickle as pickle
except ImportError:
    import pickle
from datetime import date, datetime, timedelta

from django.core.mail import send_mail
from django.contrib.contenttypes.models import ContentType
from django.contrib.auth.models import User
from django.conf import settings
from django.db import models
from django.db.models.signals import post_save
from django.template.loader import render_to_string
from django.utils.translation import ugettext_lazy as _
from django.dispatch import receiver
from django.db.models import Q

from django_extensions.db.fields import UUIDField
from activity import utils


# TODO look for fields with build-in serialization support
# TODO add some decorator/function to auto add activity to form
# TODO add proxy model

class ActivityQuerySet(models.query.QuerySet):

    def mark_for_update(self):
        return self.update(data_for_template_cached=None)

    def for_user(self, user):
        return self.filter(Q(public=True) | Q(to_user=user))

    def by_user(self, user):
        return self.filter(user=user)

    def by_object(self, obj, activity_class, content_type=None, num=''):
        if not content_type:
            content_type = ContentType.objects.get_for_model(activity_class)
        return self.filter(**{
            'content_type': content_type,
            'obj%s_id' % str(num): obj.pk
        })

    def by_type(self, activity_type):
        content_type = ContentType.objects.get(model=activity_type)
        return self.filter(content_type=content_type)

    def send_by_email(
        self, email, template_name='activity/activity_email.txt',
        subject=_("New activity on site"), **kwargs
    ):
        '''Send activity items in queryset to given email'''

        data = kwargs
        data.update({'email': email, 'activity': self})
        body = render_to_string(template_name, data)
        send_mail(subject, body, settings.DEFAULT_FROM_EMAIL, [email])


class ActivityManager(models.Manager):
    """Contain extra difficult queries"""

    def get_query_set(self):
        return ActivityQuerySet(self.model)

    def __getattr__(self, attr, *args):
        try:
            return getattr(self.__class__, attr, *args)
        except AttributeError:
            return getattr(self.get_query_set(), attr, *args)


class Activity(models.Model):
    """Store user activity in different apps. Like Facebook"""

    NONE = 0
    ADD = 1
    REMOVE = 2

    ACTION_CHOICES = (
        (NONE, _('none')),
        (ADD, _('added')),
        (REMOVE, _('removed')),
    )

    id = UUIDField(primary_key=True)
    user = models.ForeignKey(User, related_name="activity")
    time = models.DateTimeField(blank=False, null=False, auto_now_add=True)
    public = models.BooleanField(default=True)
    # if this field is set, activity feed will be shown only to this user
    to_user = models.ForeignKey(
        User, blank=True, null=True, related_name="activity_for_user"
    )
    action = models.IntegerField(blank=False, null=False)
    # Need to make effective future grouping by object
    obj_id = models.CharField(blank=True, null=True, max_length=40)
    obj2_id = models.CharField(blank=True, null=True, max_length=40)
    obj3_id = models.CharField(blank=True, null=True, max_length=40)
    obj4_id = models.CharField(blank=True, null=True, max_length=40)
    obj5_id = models.CharField(blank=True, null=True, max_length=40)
    content_type = models.ForeignKey(ContentType)
    data_for_template_cached = models.TextField(blank=True, null=True)

    objects = ActivityManager()

    def render_action(self):
        return dict(self.ACTION_CHOICES)[self.action]

    def save(self, force_insert=False, force_update=False, *args, **kwargs):
        if not force_update and self.__class__.__name__ != "Activity":
            self.content_type = ContentType.objects.get_for_model(self)
        return super(Activity, self).save(
            force_insert, force_update, *args, **kwargs
        )

    def get_or_create_data_for_template(self):
        if not self.data_for_template_cached:
            current_type_model_name = self.content_type.model
            pickled = pickle.dumps(
                getattr(self, current_type_model_name).data_for_template(self),
                protocol=pickle.HIGHEST_PROTOCOL
            )
            self.data_for_template_cached = base64.encodestring(pickled)
            self.save(force_update=True)
        return pickle.loads(base64.decodestring(self.data_for_template_cached))

    def data_for_template(self, activity):
        return {'activity': self}

    def render(self, content_type=".html"):
        """Render current activity """

        current_type_model_name = self.content_type.model
        current_type_model_class = self.content_type.model_class()
        return hasattr(current_type_model_class, 'render_html') \
               and getattr(self, current_type_model_name).render_html() \
               or render_to_string(
                    "activity/%s%s" % (current_type_model_name, content_type),
                    self.get_or_create_data_for_template()
               )

    def render_email(self):
        return self.render('_email.txt').strip(' \n')

    class Meta:
        ordering = ('-time',)
        verbose_name, verbose_name_plural = "activity", "activity"

    def __unicode__(self):
        return u"Activity"

    def mark_for_update(self):
        self.data_for_template_cached = None
        self.save()

    @property
    def pretty_date(self):
        today = date.today()
        if self.time.date() == today:
            return _('Today')
        elif self.time.date() == today - timedelta(days=1):
            return _('Yesterday')
        else:
            return False


class NotifySettings(models.Model):
    """Activity notification settings for each user"""

    HOUR = 60 * 60
    HOUR6 = 60 * 60 * 6
    HOUR12 = 60 * 60 * 12
    DAY = 60 * 60 * 24
    WEEK = 60 * 60 * 24 * 7

    FREQUENCY_CHOICES = (
        (HOUR, _('every hour')),
        (HOUR6, _('4 times per day')),
        (HOUR12, _('2 time per day')),
        (DAY, _('every day')),
        (WEEK, _('every week')),
    )

    id = UUIDField(primary_key=True)
    user = models.OneToOneField(User, related_name="notify_settings")
    frequency = models.IntegerField(
        choices=FREQUENCY_CHOICES, default=DAY, verbose_name=_('frequency')
     )
    immediately = models.ManyToManyField(ContentType, blank=True, null=True)
    last_sended = models.DateTimeField(blank=True, null=True)

    class Meta:
        ordering = ['user']

    def __unicode__(self):
        return u"%s's notify settings" % self.user

    def can_send(self, send_time=None):
        ''' check if we can send notify to user '''
        if not self.last_sended:
            return True
        if not send_time:
            send_time = datetime.now()
        return self.last_sended + timedelta(seconds=self.frequency) < send_time


@receiver(
    post_save, sender=User,
    dispatch_uid="activities.update_activity_with_updated_user_data"
)
def update_activity_with_updated_user_data(sender, instance, **kwargs):
    Activity.objects.by_user(instance).mark_for_update()


@receiver(
    post_save, sender=User,
    dispatch_uid='activities.attach_notify_settings_to_user'
)
def attach_notify_settings_to_user(sender, instance, created, **kwargs):
    if created:
        # TODO add ability to customize default immediately settings
        notify_settings = NotifySettings(user=instance)
        notify_settings.save()

utils.autodiscover()

presence/apps/vote/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _

import datetime

DAYSTATUS = (
    ('-1', 'Bad'),
    ('0', 'Neutral'),
    ('1', 'Good')
)


class UserVoteManager(models.Manager):
    def vote(self, user, vote):
        date = datetime.date.today()
        try:
            _vote = self.get(user=user, date=date)
            _vote.vote = vote
            _vote.save()
        except:
            _vote = self.create(user=user, date=date, vote=vote)
        return _vote

    def get_votes(self, user, days=7):
        today = datetime.date.today()
        _past = today - datetime.timedelta(days=days)
        return self.filter(user=user, date__range=(_past, today))


class UserVote(models.Model):
    user = models.ForeignKey(User,
        verbose_name=_("User"))
    date = models.DateField(_("Current date"))
    vote = models.CharField(_("Vote"), max_length=2,
        choices=DAYSTATUS)
    objects = UserVoteManager()

    class Meta:
        verbose_name = _("User daily vote")
        verbose_name_plural = _("User daily votes")
        ordering = ("-date",)

    def __unicode__(self):
        return self.user.username

presence/templates/activity/_user.html
{% load people_tags %}
<img src="{% gravatar activity.user.email 16 %}" alt=""/>
<a href="{{activity.user.get_profile.get_absolute_url}}">{{activity.user.get_full_name|default:activity.user.username}}</a>

presence/templates/activity/activity.html
{% load pagination_tags people_tags%} 
<section id="activity" class="main-list">
    <header>
    <h1>Latest activity</h1>
    <span class="updated">
        <time datetime="{% now "c" %}" class="relative">{% now "c" %}</time>
    </span>
    </header>
{% if activity %}
{% autopaginate activity 100 %}
{% for action in activity %}
<ul>
    {% ifchanged action.time|date:"Ymd" %}
    <li class="date">
      {% if action.pretty_date %}
        {{action.pretty_date}}
      {% else %}
        {{action.time|date:"l, d F Y"}}
      {% endif %}
    </li>
    {% endifchanged %}
    <li{% if activity.user == user%} class="my"{% endif %}>
        <span class="time">{{action.time|date:"H:i"}}</span>
        <article>{{action.render|safe}}</article>
        <p class="headline">
            <time datetime="{{action.time|date:"c"}}" class="relative">{{action.time}}</time>
        </p>
    </li>
</ul>
{% endfor %}
<div class="paginator"> {% paginate %} </div>
{% else %}
    <p class="empty">There are no shouts yet. You can be first one.</p>
{% endif %}
</section>

presence/templates/activity/base.html
{% block activity-item %}{% endblock activity-item %}

presence/templates/activity/locationactivity.html
{% extends 'activity/base.html' %}
{% load i18n %}

{% block activity-item %}
  {% include "activity/_user.html" %}
  {{ activity.render_action }}
  {% if activity.old_location %}
    {% blocktrans with old_location=activity.old_location new_location=activity.new_location  %}
      from {{ old_location }} to {{ new_location }}
    {% endblocktrans %}
  {% else %}
    {% blocktrans with new_location=activity.new_location  %}
      to {{ new_location }}
    {% endblocktrans %}
  {% endif %}
{% endblock activity-item %}

presence/templates/activity/planningactivity.html
{% extends 'activity/base.html' %}
{% load i18n %}

{% block activity-item %}
  {% include "activity/_user.html" %}
  <em class="plan-date">{{ activity.plan.date|date:'Y-m-d' }}</em>
  {% trans "planning to" %} {{ activity.plan.get_work_status_display }}
{% endblock activity-item %}

presence/templates/activity/projectactivity.html
{% extends 'activity/base.html' %}
{% load i18n %}

{% block activity-item %}
  {% include "activity/_user.html" %}
  {{ activity.render_action }}
  {% if activity.old_project %}
    {% blocktrans with old_project=activity.old_project new_project=activity.new_project  %}
      from {{ old_project }} to {{ new_project }}
    {% endblocktrans %}
  {% else %}
    {% blocktrans with new_project=activity.new_project  %}
      to {{ new_project }}
    {% endblocktrans %}
  {% endif %}
{% endblock activity-item %}

presence/templates/activity/shoutactivity.html
{% extends 'activity/base.html' %}
{% load shout_tags %}

{% block activity-item %}
<p>
  {% include "activity/_user.html" %}
  {{ activity.render_action }}:
</p>
  {{ activity.shout.message|safe|linebreaksbr }}
{% endblock activity-item %}

presence/templates/activity/stateactivity.html
{% extends 'activity/base.html' %}
{% load i18n %}

{% block activity-item %}
  {% include "activity/_user.html" %}
  {{ activity.render_action }}
  {% if activity.old_state %}
    {% blocktrans with old_state=activity.old_state new_state=activity.new_state  %}
      from {{ old_state }} to {{ new_state }}
    {% endblocktrans %}
  {% else %}
    {% blocktrans with new_state=activity.new_state  %}
      to {{ new_state }}
    {% endblocktrans %}
  {% endif %}
{% endblock activity-item %}

presence/templates/activity/voteactivity.html
{% extends 'activity/base.html' %}
{% load i18n %}

{% block activity-item %}
  {% include "activity/_user.html" %}
  {{ activity.render_action }}
  {% blocktrans with vote=activity.get_vote_display  %}
    with {{ vote }}
  {% endblocktrans %}
{% endblock activity-item %}